import { Wilaya } from '../types';

export const ALL_WILAYAS: Wilaya[] = [
  { id: 1, code: '01', name_ar: 'أدرار', name_fr: 'Adrar', region: 'South', home_delivery_price: 1200, desk_delivery_price: 800, home_delivery_days: 7, desk_delivery_days: 5, is_active: true, sort_order: 1 },
  { id: 2, code: '02', name_ar: 'الشلف', name_fr: 'Chlef', region: 'North', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 2 },
  { id: 3, code: '03', name_ar: 'الأغواط', name_fr: 'Laghouat', region: 'Centre', home_delivery_price: 800, desk_delivery_price: 500, home_delivery_days: 4, desk_delivery_days: 3, is_active: true, sort_order: 3 },
  { id: 4, code: '04', name_ar: 'أم البواقي', name_fr: 'Oum El Bouaghi', region: 'East', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 4 },
  { id: 5, code: '05', name_ar: 'باتنة', name_fr: 'Batna', region: 'East', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 5 },
  { id: 6, code: '06', name_ar: 'بجاية', name_fr: 'Béjaïa', region: 'North', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 6 },
  { id: 7, code: '07', name_ar: 'بسكرة', name_fr: 'Biskra', region: 'Centre', home_delivery_price: 800, desk_delivery_price: 500, home_delivery_days: 4, desk_delivery_days: 3, is_active: true, sort_order: 7 },
  { id: 8, code: '08', name_ar: 'بشار', name_fr: 'Béchar', region: 'South', home_delivery_price: 1200, desk_delivery_price: 800, home_delivery_days: 7, desk_delivery_days: 5, is_active: true, sort_order: 8 },
  { id: 9, code: '09', name_ar: 'البليدة', name_fr: 'Blida', region: 'North', home_delivery_price: 500, desk_delivery_price: 350, home_delivery_days: 2, desk_delivery_days: 1, is_active: true, sort_order: 9 },
  { id: 10, code: '10', name_ar: 'البويرة', name_fr: 'Bouira', region: 'North', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 10 },
  { id: 11, code: '11', name_ar: 'تمنراست', name_fr: 'Tamanrasset', region: 'South', home_delivery_price: 1500, desk_delivery_price: 1000, home_delivery_days: 10, desk_delivery_days: 7, is_active: true, sort_order: 11 },
  { id: 12, code: '12', name_ar: 'تبسة', name_fr: 'Tébessa', region: 'East', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 12 },
  { id: 13, code: '13', name_ar: 'تلمسان', name_fr: 'Tlemcen', region: 'West', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 13 },
  { id: 14, code: '14', name_ar: 'تيارت', name_fr: 'Tiaret', region: 'Centre', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 14 },
  { id: 15, code: '15', name_ar: 'تيزي وزو', name_fr: 'Tizi Ouzou', region: 'North', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 15 },
  { id: 16, code: '16', name_ar: 'الجزائر العاصمة', name_fr: 'Alger', region: 'Centre', home_delivery_price: 400, desk_delivery_price: 300, home_delivery_days: 2, desk_delivery_days: 1, is_active: true, sort_order: 16 },
  { id: 17, code: '17', name_ar: 'الجلفة', name_fr: 'Djelfa', region: 'Centre', home_delivery_price: 800, desk_delivery_price: 500, home_delivery_days: 4, desk_delivery_days: 3, is_active: true, sort_order: 17 },
  { id: 18, code: '18', name_ar: 'جيجل', name_fr: 'Jijel', region: 'North', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 18 },
  { id: 19, code: '19', name_ar: 'سطيف', name_fr: 'Sétif', region: 'East', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 19 },
  { id: 20, code: '20', name_ar: 'سعيدة', name_fr: 'Saïda', region: 'West', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 20 },
  { id: 21, code: '21', name_ar: 'سكيكدة', name_fr: 'Skikda', region: 'North', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 21 },
  { id: 22, code: '22', name_ar: 'سيدي بلعباس', name_fr: 'Sidi Bel Abbès', region: 'West', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 22 },
  { id: 23, code: '23', name_ar: 'عنابة', name_fr: 'Annaba', region: 'East', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 23 },
  { id: 24, code: '24', name_ar: 'قالمة', name_fr: 'Guelma', region: 'East', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 24 },
  { id: 25, code: '25', name_ar: 'قسنطينة', name_fr: 'Constantine', region: 'East', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 25 },
  { id: 26, code: '26', name_ar: 'المدية', name_fr: 'Médéa', region: 'Centre', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 26 },
  { id: 27, code: '27', name_ar: 'مستغانم', name_fr: 'Mostaganem', region: 'North', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 27 },
  { id: 28, code: '28', name_ar: 'المسيلة', name_fr: "M'Sila", region: 'Centre', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 28 },
  { id: 29, code: '29', name_ar: 'معسكر', name_fr: 'Mascara', region: 'West', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 29 },
  { id: 30, code: '30', name_ar: 'ورقلة', name_fr: 'Ouargla', region: 'South', home_delivery_price: 1000, desk_delivery_price: 700, home_delivery_days: 5, desk_delivery_days: 4, is_active: true, sort_order: 30 },
  { id: 31, code: '31', name_ar: 'وهران', name_fr: 'Oran', region: 'West', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 31 },
  { id: 32, code: '32', name_ar: 'البيض', name_fr: 'El Bayadh', region: 'Centre', home_delivery_price: 900, desk_delivery_price: 600, home_delivery_days: 5, desk_delivery_days: 4, is_active: true, sort_order: 32 },
  { id: 33, code: '33', name_ar: 'إليزي', name_fr: 'Illizi', region: 'South', home_delivery_price: 1500, desk_delivery_price: 1000, home_delivery_days: 10, desk_delivery_days: 7, is_active: true, sort_order: 33 },
  { id: 34, code: '34', name_ar: 'برج بوعريريج', name_fr: 'Bordj Bou Arréridj', region: 'East', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 34 },
  { id: 35, code: '35', name_ar: 'بومرداس', name_fr: 'Boumerdès', region: 'North', home_delivery_price: 500, desk_delivery_price: 350, home_delivery_days: 2, desk_delivery_days: 1, is_active: true, sort_order: 35 },
  { id: 36, code: '36', name_ar: 'الطارف', name_fr: 'El Tarf', region: 'East', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 36 },
  { id: 37, code: '37', name_ar: 'تندوف', name_fr: 'Tindouf', region: 'South', home_delivery_price: 1500, desk_delivery_price: 1000, home_delivery_days: 10, desk_delivery_days: 7, is_active: true, sort_order: 37 },
  { id: 38, code: '38', name_ar: 'تيسمسيلت', name_fr: 'Tissemsilt', region: 'Centre', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 38 },
  { id: 39, code: '39', name_ar: 'الوادي', name_fr: 'El Oued', region: 'South', home_delivery_price: 1000, desk_delivery_price: 700, home_delivery_days: 5, desk_delivery_days: 4, is_active: true, sort_order: 39 },
  { id: 40, code: '40', name_ar: 'خنشلة', name_fr: 'Khenchela', region: 'East', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 40 },
  { id: 41, code: '41', name_ar: 'سوق أهراس', name_fr: 'Souk Ahras', region: 'East', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 41 },
  { id: 42, code: '42', name_ar: 'تيبازة', name_fr: 'Tipaza', region: 'North', home_delivery_price: 500, desk_delivery_price: 350, home_delivery_days: 2, desk_delivery_days: 1, is_active: true, sort_order: 42 },
  { id: 43, code: '43', name_ar: 'ميلة', name_fr: 'Mila', region: 'East', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 43 },
  { id: 44, code: '44', name_ar: 'عين الدفلى', name_fr: 'Aïn Defla', region: 'Centre', home_delivery_price: 600, desk_delivery_price: 400, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 44 },
  { id: 45, code: '45', name_ar: 'النعامة', name_fr: 'Naâma', region: 'South', home_delivery_price: 1000, desk_delivery_price: 700, home_delivery_days: 5, desk_delivery_days: 4, is_active: true, sort_order: 45 },
  { id: 46, code: '46', name_ar: 'عين تموشنت', name_fr: 'Aïn Témouchent', region: 'West', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 46 },
  { id: 47, code: '47', name_ar: 'غرداية', name_fr: 'Ghardaïa', region: 'Centre', home_delivery_price: 900, desk_delivery_price: 600, home_delivery_days: 5, desk_delivery_days: 4, is_active: true, sort_order: 47 },
  { id: 48, code: '48', name_ar: 'غليزان', name_fr: 'Relizane', region: 'West', home_delivery_price: 700, desk_delivery_price: 450, home_delivery_days: 3, desk_delivery_days: 2, is_active: true, sort_order: 48 },
  { id: 49, code: '49', name_ar: 'تيميمون', name_fr: 'Timimoun', region: 'South', home_delivery_price: 1500, desk_delivery_price: 1000, home_delivery_days: 10, desk_delivery_days: 7, is_active: true, sort_order: 49 },
  { id: 50, code: '50', name_ar: 'برج باجي مختار', name_fr: 'Bordj Badji Mokhtar', region: 'South', home_delivery_price: 1500, desk_delivery_price: 1000, home_delivery_days: 10, desk_delivery_days: 7, is_active: true, sort_order: 50 },
  { id: 51, code: '51', name_ar: 'أولاد جلال', name_fr: 'Ouled Djellal', region: 'Centre', home_delivery_price: 800, desk_delivery_price: 500, home_delivery_days: 4, desk_delivery_days: 3, is_active: true, sort_order: 51 },
  { id: 52, code: '52', name_ar: 'بني عباس', name_fr: 'Béni Abbès', region: 'South', home_delivery_price: 1200, desk_delivery_price: 800, home_delivery_days: 7, desk_delivery_days: 5, is_active: true, sort_order: 52 },
  { id: 53, code: '53', name_ar: 'عين صالح', name_fr: 'In Salah', region: 'South', home_delivery_price: 1500, desk_delivery_price: 1000, home_delivery_days: 10, desk_delivery_days: 7, is_active: true, sort_order: 53 },
  { id: 54, code: '54', name_ar: 'عين قزام', name_fr: 'In Guezzam', region: 'South', home_delivery_price: 1500, desk_delivery_price: 1000, home_delivery_days: 10, desk_delivery_days: 7, is_active: true, sort_order: 54 },
  { id: 55, code: '55', name_ar: 'تقرت', name_fr: 'Touggourt', region: 'South', home_delivery_price: 1000, desk_delivery_price: 700, home_delivery_days: 5, desk_delivery_days: 4, is_active: true, sort_order: 55 },
  { id: 56, code: '56', name_ar: 'جانت', name_fr: 'Djanet', region: 'South', home_delivery_price: 1500, desk_delivery_price: 1000, home_delivery_days: 10, desk_delivery_days: 7, is_active: true, sort_order: 56 },
  { id: 57, code: '57', name_ar: 'المغير', name_fr: "El M'Ghair", region: 'Centre', home_delivery_price: 900, desk_delivery_price: 600, home_delivery_days: 5, desk_delivery_days: 4, is_active: true, sort_order: 57 },
  { id: 58, code: '58', name_ar: 'المنيعة', name_fr: 'El Meniaa', region: 'Centre', home_delivery_price: 900, desk_delivery_price: 600, home_delivery_days: 5, desk_delivery_days: 4, is_active: true, sort_order: 58 }
];

export const ALGERIAN_WILAYAS = ALL_WILAYAS;
