-- Seed categories
INSERT INTO categories (name_ar, name_fr, slug, description_ar, description_fr, sort_order, is_active) VALUES
('الإلكترونيات', 'Électronique', 'electronics', 'أجهزة إلكترونية وملحقاتها', 'Appareils électroniques et accessoires', 1, true),
('الهواتف الذكية', 'Smartphones', 'smartphones', 'أحدث الهواتف الذكية', 'Derniers smartphones', 2, true),
('أجهزة الكمبيوتر', 'Ordinateurs', 'computers', 'حواسيب وملحقاتها', 'Ordinateurs et accessoires', 3, true),
('الأزياء', 'Mode', 'fashion', 'ملابس وأحذية للرجال والنساء', 'Vêtements et chaussures', 4, true),
('المنزل والمطبخ', 'Maison & Cuisine', 'home-kitchen', 'كل ما يحتاجه منزلك', 'Tout pour la maison', 5, true),
('الجمال والعناية', 'Beauté & Soins', 'beauty', 'منتجات التجميل والعناية', 'Produits de beauté', 6, true),
('الرياضة واللياقة', 'Sport & Fitness', 'sports', 'معدات رياضية ولياقة', 'Équipements sportifs', 7, true),
('الألعاب', 'Jeux & Jouets', 'toys', 'ألعاب للأطفال', 'Jeux et jouets', 8, true);

-- Seed products with Pexels images
INSERT INTO products (name_ar, name_fr, slug, description_ar, description_fr, short_description_ar, short_description_fr, category_id, sku, price, compare_price, cost_price, stock_quantity, images, is_featured, is_flash_sale, flash_sale_ends_at, rating, review_count, sales_count) VALUES
('سماعات بلوتوث لاسلكية', 'Écouteurs Bluetooth Sans Fil', 'wireless-bluetooth-earbuds', 'سماعات بلوتوث لاسلكية عالية الجودة مع عزل الضوضاء وعمر بطارية طويل', 'Écouteurs Bluetooth haute qualité avec réduction du bruit et longue autonomie', 'سماعات لاسلكية بجودة صوت استثنائية', 'Écouteurs sans fil avec qualité sonore exceptionnelle', (SELECT id FROM categories WHERE slug='electronics'), 'ELEC-001', 4500, 6500, 2200, 150, '["https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/3780683/pexels-photo-3780683.jpeg?auto=compress&cs=tinysrgb&w=800"]', true, true, now() + interval '3 days', 4.5, 23, 145),

('ساعة ذكية رياضية', 'Montre Connectée Sport', 'smart-watch-sport', 'ساعة ذكية مع تتبع اللياقة البدنية ومراقبة معدل ضربات القلب', 'Montre connectée avec suivi fitness et moniteur cardiaque', 'ساعة ذكية متعددة الوظائف', 'Montre connectée multifonction', (SELECT id FROM categories WHERE slug='electronics'), 'ELEC-002', 8500, 12000, 4000, 80, '["https://images.pexels.com/photos/393047/pexels-photo-393047.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=800"]', true, false, null, 4.3, 18, 92),

('هاتف ذكي 256GB', 'Smartphone 256GB', 'smartphone-256gb', 'هاتف ذكي بشاشة AMOLED وكاميرا 108 ميجابكسل وذاكرة 256 جيجابايت', 'Smartphone avec écran AMOLED, caméra 108MP et 256GB de stockage', 'هاتف ذكي بكاميرا احترافية', 'Smartphone avec caméra professionnelle', (SELECT id FROM categories WHERE slug='smartphones'), 'PHONE-001', 45000, 55000, 32000, 50, '["https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/1841841/pexels-photo-1841841.jpeg?auto=compress&cs=tinysrgb&w=800"]', true, true, now() + interval '2 days', 4.7, 45, 230),

('حاسوب محمول 15.6 بوصة', 'Ordinateur Portable 15.6"', 'laptop-15-6', 'حاسوب محمول بمعالج Intel Core i7 وذاكرة 16GB وقرص SSD 512GB', 'Ordinateur portable Intel Core i7, 16GB RAM, SSD 512GB', 'حاسوب قوي للأعمال والألعاب', 'Ordinateur puissant pour travail et jeux', (SELECT id FROM categories WHERE slug='computers'), 'COMP-001', 95000, 110000, 70000, 25, '["https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=800"]', true, false, null, 4.6, 12, 45),

('قميص رجالي كلاسيكي', 'Chemise Classique Homme', 'classic-mens-shirt', 'قميص رجالي أنيق بقطن عالي الجودة، مناسب للمناسبات الرسمية', 'Chemise homme élégante en coton de haute qualité', 'قميص قطني أنيق', 'Chemise en coton élégante', (SELECT id FROM categories WHERE slug='fashion'), 'FASH-001', 2500, 3500, 1200, 200, '["https://images.pexels.com/photos/996331/pexels-photo-996331.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/297881/pexels-photo-297881.jpeg?auto=compress&cs=tinysrgb&w=800"]', false, false, null, 4.2, 8, 67),

('حذاء رياضي للجري', 'Chaussures de Running', 'running-shoes', 'حذاء رياضي خفيف الوزن مع نعل مريح للجري والمشي', 'Chaussures de sport légères avec semelle confortable', 'حذاء رياضي مريح', 'Chaussures de sport confortables', (SELECT id FROM categories WHERE slug='sports'), 'SPORT-001', 5500, 7500, 2800, 120, '["https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/1639729/pexels-photo-1639729.jpeg?auto=compress&cs=tinysrgb&w=800"]', true, true, now() + interval '5 days', 4.4, 31, 178),

('طقم أواني طبخ 10 قطع', 'Set de Casseroles 10 Pièces', 'cookware-set-10', 'طقم أواني طبخ من الستانلس ستيل يتكون من 10 قطع', 'Set de casseroles en acier inoxydable 10 pièces', 'طقم أواني طبخ متكامل', 'Set de casseroles complet', (SELECT id FROM categories WHERE slug='home-kitchen'), 'HOME-001', 7500, 10000, 3500, 60, '["https://images.pexels.com/photos/4226807/pexels-photo-4226807.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/4226796/pexels-photo-4226796.jpeg?auto=compress&cs=tinysrgb&w=800"]', false, false, null, 4.5, 15, 89),

('كريم مرطب للوجه', 'Crème Hydratante Visage', 'face-moisturizer', 'كريم مرطب طبيعي للوجه يغذي البشرة ويحافظ على نضارتها', 'Crème hydratante naturelle pour le visage', 'كريم مرطب طبيعي للبشرة', 'Crème hydratante naturelle', (SELECT id FROM categories WHERE slug='beauty'), 'BEAUTY-001', 1800, 2500, 800, 300, '["https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg?auto=compress&cs=tinysrgb&w=800"]', false, true, now() + interval '4 days', 4.6, 52, 312),

('لوحة مفاتيح ميكانيكية', 'Clavier Mécanique', 'mechanical-keyboard', 'لوحة مفاتيح ميكانيكية RGB مع إضاءة خلفية قابلة للتخصيص', 'Clavier mécanique RGB avec rétroéclairage personnalisable', 'لوحة مفاتيح للألعاب', 'Clavier gaming haute performance', (SELECT id FROM categories WHERE slug='computers'), 'COMP-002', 6500, 9000, 3000, 90, '["https://images.pexels.com/photos/211525/pexels-photo-211525.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=800"]', true, false, null, 4.7, 19, 76),

('حقيبة ظهر عصرية', 'Sac à Dos Moderne', 'modern-backpack', 'حقيبة ظهر أنيقة ومقاومة للماء مع جيوب متعددة وحامل لابتوب', 'Sac à dos élégant et imperméable avec compartiment laptop', 'حقيبة ظهر عملية وأنيقة', 'Sac à dos pratique et élégant', (SELECT id FROM categories WHERE slug='fashion'), 'FASH-002', 3500, 5000, 1500, 150, '["https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/1170200/pexels-photo-1170200.jpeg?auto=compress&cs=tinysrgb&w=800"]', false, false, null, 4.3, 11, 54),

('كاميرا رقمية احترافية', 'Caméra Numérique Pro', 'pro-digital-camera', 'كاميرا رقمية احترافية بدقة 24 ميجابكسل وفيديو 4K', 'Caméra numérique professionnelle 24MP vidéo 4K', 'كاميرا احترافية للتصوير', 'Caméra professionnelle', (SELECT id FROM categories WHERE slug='electronics'), 'ELEC-003', 65000, 80000, 45000, 15, '["https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=800"]', true, false, null, 4.8, 7, 23),

('شاحن سريع 65W', 'Chargeur Rapide 65W', 'fast-charger-65w', 'شاحن سريع 65 واط متوافق مع جميع الأجهزة الذكية', 'Chargeur rapide 65W compatible tous appareils', 'شاحن سريع لجميع الأجهزة', 'Chargeur rapide universel', (SELECT id FROM categories WHERE slug='electronics'), 'ELEC-004', 1800, 2500, 700, 250, '["https://images.pexels.com/photos/456054/pexels-photo-456054.jpeg?auto=compress&cs=tinysrgb&w=800"]', false, true, now() + interval '1 day', 4.4, 28, 198),

('دمى تعليمية للأطفال', 'Jouets Éducatifs Enfants', 'educational-toys', 'مجموعة ألعاب تعليمية تنمي مهارات الأطفال', 'Ensemble de jouets éducatifs', 'ألعاب تعليمية ممتعة', 'Jouets éducatifs amusants', (SELECT id FROM categories WHERE slug='toys'), 'TOYS-001', 2200, 3000, 900, 180, '["https://images.pexels.com/photos/3661193/pexels-photo-3661193.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/207891/pexels-photo-207891.jpeg?auto=compress&cs=tinysrgb&w=800"]', false, false, null, 4.5, 14, 87),

('دراجة هوائية جبلية', 'Vélo de Montagne', 'mountain-bike', 'دراجة هوائية جبلية بإطار قوي ومقعد مريح وفرامل قرصية', 'Vélo de montagne avec cadre robuste et freins à disque', 'دراجة جبلية متينة', 'Vélo tout terrain robuste', (SELECT id FROM categories WHERE slug='sports'), 'SPORT-002', 28000, 35000, 18000, 20, '["https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=800", "https://images.pexels.com/photos/161172/cycling-bike-trail-sport-161172.jpeg?auto=compress&cs=tinysrgb&w=800"]', true, false, null, 4.6, 9, 34),

('مكواة شعر احترافية', 'Fer à Lisser Professionnel', 'pro-hair-straightener', 'مكواة شعر احترافية بألواح سيراميك حرارة قابلة للتعديل', 'Fer à lisser professionnel avec plaques céramique', 'مكواة شعر للتصميم الاحترافي', 'Fer à lisser professionnel', (SELECT id FROM categories WHERE slug='beauty'), 'BEAUTY-002', 3200, 4500, 1400, 100, '["https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=800"]', false, false, null, 4.3, 16, 102);
